hostname allied-lab
switch 1 provision x540L-28
vlan database
 vlan 10 name OFFICE
 vlan 20 name GUEST
 vlan 90 name SERVER
 vlan 10,20,90 state enable
!
access-list hardware OFFICE
 permit tcp 10.44.1.0/24 10.44.9.0/24 eq 443
 deny ip any any
!
access-list hardware GUEST
 deny ip any any
!
vlan access-map OFFICE_MAP
 match access-group OFFICE
!
vlan access-map GUEST_MAP
 match access-group GUEST
!
interface vlan10
 ip address 10.44.1.1/24
interface vlan20
 ip address 10.44.2.1/24
interface vlan90
 ip address 10.44.9.1/24
!
vlan filter OFFICE_MAP vlan-list 10 input
vlan filter GUEST_MAP vlan-list 20 input
