! AlliedWare Plus 5.5
hostname allied01
vlan 120 name MGMT-AW
interface port1.0.1
 switchport access vlan 120
interface vlan120
 ip address 10.120.0.1/24
 access-group MGMT-IN
access-list MGMT-IN permit tcp 10.120.0.0/24 any eq 22
access-list MGMT-IN deny ip 10.120.0.0/24 any
ip route 0.0.0.0/0 10.120.0.254
