!Version ArubaOS-CX FL.10.13
hostname aoscx01
vlan 100
 name SERVER-CX
interface 1/1/1
 description Server uplink
 vlan access 100
interface vlan 100
 ip address 10.100.0.1/24
 apply access-list ip SERVER-IN in
access-list ip SERVER-IN
 10 permit tcp 10.100.0.0/24 any eq 443
 20 deny tcp 10.100.0.0/24 any eq 22
ip route 0.0.0.0/0 10.100.0.254
