hostname eos01
service routing protocols model multi-agent
vlan 110
 name APP-EOS
interface Ethernet1
 description Application host
 switchport access vlan 110
interface Vlan110
 ip address 10.110.0.1/24
 ip access-group APP-IN in
ip access-list APP-IN
 10 permit tcp 10.110.0.0/24 any eq 8443
 20 deny ip 10.110.0.0/24 any
ip route 0.0.0.0/0 10.110.0.254
