config system global
    set hostname fortigate01
end
config system interface
    edit "port1"
        set alias "Internet"
        set ip 203.0.113.1 255.255.255.248
    next
    edit "port2"
        set alias "DMZ"
        set ip 172.16.100.1 255.255.255.0
    next
end
config system zone
    edit "WAN"
        set interface "port1"
    next
    edit "DMZ"
        set interface "port2"
    next
end
config firewall address
    edit "WEB-SERVER"
        set subnet 172.16.100.10 255.255.255.255
    next
end
config firewall service custom
    edit "WEB-HTTPS"
        set tcp-portrange 443
    next
end
config firewall policy
    edit 10
        set name "Internet-to-Web"
        set srcintf "WAN"
        set dstintf "DMZ"
        set srcaddr "all"
        set dstaddr "WEB-SERVER"
        set action accept
        set service "WEB-HTTPS"
        set nat enable
    next
end
config router static
    edit 1
        set dst 0.0.0.0 0.0.0.0
        set gateway 203.0.113.6
        set device "port1"
    next
end
