set system host-name srx01
set interfaces ge-0/0/1 unit 0 family inet address 10.0.10.1/24
set interfaces ge-0/0/2 unit 0 family inet address 203.0.113.2/29
set security zones security-zone trust interfaces ge-0/0/1.0
set security zones security-zone untrust interfaces ge-0/0/2.0
set security zones security-zone trust address-book address LAN-NET 10.0.10.0/24
set security policies from-zone trust to-zone untrust policy WEB match source-address LAN-NET
set security policies from-zone trust to-zone untrust policy WEB match destination-address any
set security policies from-zone trust to-zone untrust policy WEB match application junos-https
set security policies from-zone trust to-zone untrust policy WEB then permit
