config system global
 set hostname fortios-lab
end
config system interface
 edit "office"
  set ip 10.44.1.1 255.255.255.0
 next
 edit "guest"
  set ip 10.44.2.1 255.255.255.0
 next
 edit "server"
  set ip 10.44.9.1 255.255.255.0
 next
 edit "wan"
  set ip 198.51.100.1 255.255.255.0
 next
end
config firewall vip
 edit "WEB"
  set extip 198.51.100.10
  set mappedip "10.44.9.20"
  set extintf "wan"
  set portforward enable
  set protocol tcp
  set extport 8443
  set mappedport 443
 next
end
config firewall policy
 edit 10
  set srcintf "office"
  set dstintf "server"
  set srcaddr "all"
  set dstaddr "all"
  set action deny
  set schedule "always"
  set service "HTTPS"
 next
 edit 20
  set srcintf "guest"
  set dstintf "office"
  set srcaddr "all"
  set dstaddr "all"
  set action deny
  set schedule "always"
  set service "ALL"
 next
 edit 30
  set srcintf "wan"
  set dstintf "server"
  set srcaddr "all"
  set dstaddr "WEB"
  set action deny
  set schedule "always"
  set service "HTTPS"
 next
end
