import { expect, test, type Page } from "@playwright/test";
import { readFileSync } from "node:fs";

const original = readFileSync(new URL("./fixtures/audit.conf", import.meta.url), "utf8");
async function importConfig(page: Page, raw: string, name: string) {
  await page.getByRole("button", { name: "Config Import", exact: true }).click();
  await page.getByLabel("Snapshot名").fill(name);
  await page.getByLabel("設定ファイルを選択").setInputFiles({ name: "audit.conf", mimeType: "text/plain", buffer: Buffer.from(raw) });
  await page.getByRole("button", { name: "検出プレビュー" }).click();
  await expect(page.getByLabel("audit.conf のNetwork OS")).toBeVisible();
  await page.getByLabel("audit.conf のSite").fill("Integration Lab");
  const response = page.waitForResponse(r => r.url().includes("/api/configs/import"));
  await page.getByRole("button", { name: "Import", exact: true }).click();
  expect((await response).status()).toBe(200);
  await expect(page.getByRole("dialog", { name: "機器設定を解析" })).toBeHidden();
}

test("実API: Import・保存・Matrix・Path・再Import・Diff・Exportを通して確認する", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/");
  await importConfig(page, original, "before");
  await page.reload();
  await expect(page.locator(".matrix")).toContainText("USERS");
  const cells = await (await page.request.get("/api/matrix?protocol=tcp&port=443")).json();
  expect(cells.cells.find((cell: any) => cell.source === "audit-vlan-10" && cell.destination === "audit-vlan-20").result).toBe("ALLOW");
  await page.getByRole("button", { name: "Topology / Path" }).click();
  await page.getByLabel("Source", { exact: true }).selectOption("audit-vlan-10");
  await page.getByLabel("Destination", { exact: true }).selectOption("audit-vlan-20");
  await page.getByRole("button", { name: "経路を解析" }).click();
  await expect(page.locator(".path-verdict .status")).toHaveText("許可");
  await expect(page.locator(".hop-list")).toContainText("CHECK / Rule 10");
  // Import while Path remains mounted: the view must refresh its topology.
  const changed = original.replace("10 permit tcp", "10 deny tcp").replace("name SERVERS", "name UPDATED-SERVERS");
  await importConfig(page, changed, "after");
  await expect(page.getByLabel("Destination", { exact: true })).toContainText("UPDATED-SERVERS");
  await expect(page.locator(".path-result")).toHaveCount(0);
  await page.getByRole("button", { name: "経路を解析" }).click();
  await expect(page.locator(".path-verdict .status")).toHaveText("拒否");
  await page.getByRole("button", { name: "Snapshot Diff" }).click();
  await expect(page.locator(".diff-summary")).toBeVisible();
  await expect(page.locator(".diff-summary")).toContainText("変更ルール");
  const diff = await (await page.request.get("/api/diff")).json();
  expect(diff.summary.changed_rules).toBe(1);
  await page.getByLabel("比較Protocol").selectOption("tcp");
  await page.getByLabel("比較Port").fill("443");
  await page.getByRole("button", { name: "条件を適用" }).click();
  await expect(page.locator(".diff-query-scope")).toHaveText("経路評価: TCP / 443");
  await expect(page.locator(".comm-change").first()).toContainText("DENY TCP/443");
  await page.locator(".comm-change").first().getByText("変更前後の判定根拠").click();
  await expect(page.locator(".comm-change details").first()).toContainText("変更前:");
  await page.getByLabel("比較Port").fill("22");
  await page.getByRole("button", { name: "条件を適用" }).click();
  await expect(page.locator(".diff-query-scope")).toHaveText("経路評価: TCP / 22");
  await expect(page.getByText("通信可否の変更はありません", { exact: true })).toBeVisible();
  await page.getByLabel("比較Protocol").selectOption("icmp");
  await page.getByRole("button", { name: "条件を適用" }).click();
  await expect(page.locator(".diff-page [role=alert]")).toContainText("port requires");
  await expect(page.locator(".diff-summary")).toHaveCount(0);
  await page.getByLabel("比較Protocol").selectOption("");
  await page.getByLabel("比較Port").fill("");
  await page.getByRole("button", { name: "条件を適用" }).click();
  await expect(page.locator(".diff-query-scope")).toContainText("設定ルールの概要");
  await page.getByRole("button", { name: "Parser Debug" }).click();
  const downloading = page.waitForEvent("download");
  await page.getByRole("button", { name: "JSON Export" }).click();
  const download = await downloading;
  expect(download.suggestedFilename()).toBe("audit-canonical.json");
  const exported = readFileSync((await download.path())!, "utf8");
  expect(JSON.parse(exported).device.site).toBe("Integration Lab");
  expect(exported).not.toContain("synthetic-test-community");
  // A more-specific route with an unreachable gateway partitions the subnet end to end.
  await importConfig(page, original + "\nip route 10.0.9.128 255.255.255.128 192.0.2.99\n", "ranges");
  await page.getByRole("button", { name: "Topology / Path" }).click();
  await page.getByLabel("Source", { exact: true }).selectOption("audit-vlan-10");
  await page.getByLabel("Destination", { exact: true }).selectOption("audit-vlan-20");
  await page.getByRole("button", { name: "経路を解析" }).click();
  await expect(page.getByRole("button", { name: "経路 1: ALLOW", exact: true })).toContainText("10.0.9.0/25");
  await page.getByRole("button", { name: "経路 2: NO_ROUTE", exact: true }).click();
  await expect(page.locator(".path-options")).toContainText("10.0.9.128/25");
  await page.getByRole("button", { name: "ポリシーマトリクス", exact: true }).click();
  await page.getByLabel("ポート", { exact: true }).fill("443");
  const rangeCell = page.locator('button[title^="USERS (audit) → SERVERS"]');
  await expect(rangeCell).toHaveClass(/partial/);
  await rangeCell.click();
  await expect(page.getByLabel("宛先範囲別の判定")).toContainText("10.0.9.128/25");
  await expect(page.getByLabel("宛先範囲別の判定")).toContainText("10.0.9.0/25");
  expect(errors).toEqual([]);
});


test("実API: FortiOS VIPの取り込み・変換後Policy・NAT表示を確認する", async ({ page }) => {
  const raw = readFileSync(new URL("./fixtures/fortios-vip.conf", import.meta.url), "utf8");
  await page.goto("/");
  await importConfig(page, raw, "fortios-vip");
  await page.reload();
  await page.getByRole("button", { name: "Topology / Path" }).click();
  await page.getByLabel("Source", { exact: true }).selectOption("fg-if-wan");
  await page.getByLabel("Destination", { exact: true }).selectOption("fg-if-wan");
  await page.getByLabel("Source IP", { exact: true }).fill("198.51.100.55");
  await page.getByLabel("Destination IP", { exact: true }).fill("198.51.100.10");
  await page.getByLabel("Port", { exact: true }).fill("8443");
  await page.getByRole("button", { name: "経路を解析" }).click();
  await expect(page.locator(".path-verdict .status")).toHaveText("許可");
  await expect(page.locator(".hop-list")).toContainText("NAT: WEB");
  await expect(page.locator(".hop-list")).toContainText("10.0.9.20/32 (port 443)");
  await expect(page.locator(".path-chain")).toContainText("LAN");
  // The VIP policy must not permit direct access to the mapped host.
  await page.getByLabel("Destination", { exact: true }).selectOption("fg-if-lan");
  await page.getByLabel("Destination IP", { exact: true }).fill("10.0.9.20");
  await page.getByLabel("Port", { exact: true }).fill("443");
  await page.getByRole("button", { name: "経路を解析" }).click();
  await expect(page.locator(".path-verdict .status")).toHaveText("拒否");
});

test("実API: 大規模Matrixのページと検索は表示対象だけ解析する", async ({ page }) => {
  let raw = "version 17.12\nhostname scale\n";
  for (let i = 1; i <= 30; i++) raw += `vlan ${i}\n name NET${i}\ninterface Vlan${i}\n ip address 10.0.${i}.1 255.255.255.0\n ip access-group CHECK in\n`;
  raw += "ip access-list extended CHECK\n 10 permit ip any any\n";
  await page.goto("/");
  await importConfig(page, raw, "scale");
  await expect(page.locator(".matrix td")).toHaveCount(625);
  await page.getByLabel("プロトコル", { exact: true }).selectOption("tcp");
  await expect(page.locator(".matrix td")).toHaveCount(625);
  const response = page.waitForResponse(r => r.url().includes("source_ids=scale-vlan-26"));
  await page.getByRole("button", { name: "送信元の次のページ" }).click();
  const data = await (await response).json();
  expect(data.protocol).toBe("tcp");
  expect(data.window.source_ids).toHaveLength(5);
  expect(data.cells).toHaveLength(125);
  await page.locator('button[title="NET26 (scale) → NET1 (scale)"]').click();
  await expect(page.getByRole("dialog", { name: "通信判定の詳細" })).toContainText("TCP/ANY");
  await page.getByRole("button", { name: "詳細を閉じる" }).click();
  await page.getByLabel("Segmentを検索").fill("NET30");
  await expect(page.locator(".matrix td")).toHaveCount(1);
  await expect(page.locator('button[title="NET30 (scale) → NET30 (scale)"]')).toBeVisible();
});

test("実API: Snapshot切替・名前変更・削除・最後のSnapshot削除", async ({ page }) => {
  // This suite runs against a dedicated temporary database, never the app DB.
  for (const item of await (await page.request.get('/api/snapshots')).json())
    expect((await page.request.delete(`/api/snapshots/${item.id}`)).status()).toBe(204);
  await page.goto('/');
  await importConfig(page, original, 'history-before');
  const before = (await (await page.request.get('/api/snapshots')).json())[0].id;
  await importConfig(page, original.replace('10 permit tcp', '10 deny tcp'), 'history-after');
  const after = (await (await page.request.get('/api/snapshots')).json())[0].id;
  await expect(page.getByLabel('解析対象Snapshot')).toHaveValue(after);
  await page.getByLabel('解析対象Snapshot').selectOption(before);
  await page.getByRole('button', { name: 'Topology / Path' }).click();
  await page.getByLabel('Source', { exact: true }).selectOption('audit-vlan-10');
  await page.getByLabel('Destination', { exact: true }).selectOption('audit-vlan-20');
  const oldPath = page.waitForRequest(r => r.url().includes('/api/reachability?'));
  await page.getByRole('button', { name: '経路を解析' }).click();
  expect(new URL((await oldPath).url()).searchParams.get('snapshot_id')).toBe(before);
  await expect(page.locator('.path-verdict .status')).toHaveText('許可');
  await page.getByLabel('解析対象Snapshot').selectOption(after);
  await expect(page.locator('.path-result')).toHaveCount(0);
  await page.getByLabel('Source', { exact: true }).selectOption('audit-vlan-10');
  await page.getByLabel('Destination', { exact: true }).selectOption('audit-vlan-20');
  await page.getByRole('button', { name: '経路を解析' }).click();
  await expect(page.locator('.path-verdict .status')).toHaveText('拒否');
  await page.getByLabel('解析対象Snapshot').selectOption(before);
  await page.reload();
  await expect(page.getByLabel('解析対象Snapshot')).toHaveValue(before);
  await page.getByRole('button', { name: 'Parser Debug' }).click();
  const downloading = page.waitForEvent('download');
  await page.getByRole('button', { name: 'JSON Export' }).click();
  const exported = JSON.parse(readFileSync((await (await downloading).path())!, 'utf8'));
  expect(exported.policies.find((p: any) => p.sequence === 10).action).toBe('permit');
  await page.getByRole('button', { name: '履歴を管理' }).click();
  const row = page.getByRole('article', { name: 'Snapshot history-before', exact: true });
  await row.getByRole('button', { name: '名前変更' }).click();
  await page.getByLabel('新しいSnapshot名').fill('変更前の保存構成');
  await page.getByRole('button', { name: '保存', exact: true }).click();
  const renamed = page.getByRole('article', { name: 'Snapshot 変更前の保存構成', exact: true });
  await expect(renamed).toContainText('選択中');
  await renamed.getByRole('button', { name: '削除', exact: true }).click();
  const confirmation = page.getByRole('dialog', { name: 'Snapshotを削除しますか？' });
  await expect(confirmation).toContainText('変更前の保存構成');
  await confirmation.getByRole('button', { name: 'キャンセル' }).click();
  expect((await (await page.request.get('/api/snapshots')).json()).length).toBe(2);
  await renamed.getByRole('button', { name: '削除', exact: true }).click();
  await confirmation.getByRole('button', { name: '削除を実行' }).click();
  await expect(page.getByLabel('解析対象Snapshot')).toHaveValue(after);
  expect((await page.request.get(`/api/matrix?limit=25&snapshot_id=${before}`)).status()).toBe(404);
  await page.getByRole('article', { name: 'Snapshot history-after', exact: true }).getByRole('button', { name: '削除', exact: true }).click();
  await confirmation.getByRole('button', { name: '削除を実行' }).click();
  await expect(page.getByLabel('解析対象Snapshot')).toHaveCount(0);
  await expect(page.getByText('まだSnapshotがありません。Config Importから設定を取り込んでください。')).toBeVisible();
  await page.getByRole('button', { name: 'ポリシーマトリクス', exact: true }).click();
  await expect(page.getByText('まだネットワークがありません')).toBeVisible();
});


test("実API: Policyの宛先範囲をPath・Matrix・Diffで比較できる", async ({ page }) => {
  await page.goto("/");
  await importConfig(page, original.replace("10.0.9.0 0.0.0.255 eq 443", "10.0.9.0 0.0.0.127 eq 443"), "lower-half");
  await page.getByLabel("ポート", { exact: true }).fill("443");
  const cell = page.locator('button[title^="USERS (audit) → SERVERS"]');
  await expect(cell).toHaveClass(/partial/);
  await cell.click();
  await expect(page.getByLabel("宛先範囲別の判定")).toContainText("10.0.9.0/25");
  await expect(page.getByLabel("宛先範囲別の判定")).toContainText("10.0.9.128/25");
  await page.locator(".shade").click({ position: { x: 5, y: 5 } });
  await page.getByRole("button", { name: "Topology / Path" }).click();
  await page.getByLabel("Source", { exact: true }).selectOption("audit-vlan-10");
  await page.getByLabel("Destination", { exact: true }).selectOption("audit-vlan-20");
  await page.getByRole("button", { name: "経路を解析" }).click();
  await expect(page.getByRole("button", { name: "経路 1: ALLOW", exact: true })).toContainText("10.0.9.0/25");
  await expect(page.getByRole("button", { name: "経路 2: DENY", exact: true })).toContainText("10.0.9.128/25");
  await importConfig(page, original.replace("10.0.9.0 0.0.0.255 eq 443", "10.0.9.128 0.0.0.127 eq 443"), "upper-half");
  await page.getByRole("button", { name: "Snapshot Diff" }).click();
  await page.getByLabel("比較Protocol").selectOption("tcp");
  await page.getByLabel("比較Port").fill("443");
  await page.getByRole("button", { name: "条件を適用" }).click();
  await expect(page.locator(".diff-query-scope")).toHaveText("経路評価: TCP / 443");
  const row = page.locator(".comm-change").filter({ hasText: "USERS" }).filter({ hasText: "SERVERS" }).first();
  await expect(row.locator(".result-shift .status")).toHaveCount(2);
  await row.getByText("宛先範囲ごとの変更前後").click();
  await expect(row.locator(".diff-ranges")).toContainText("10.0.9.128/25");
  await expect(row.locator(".diff-ranges")).toContainText("10.0.9.0/25");
  await page.setViewportSize({ width: 390, height: 1000 });
  if (!await page.locator(".app").evaluate(el => el.classList.contains("sidebar-collapsed")))
    await page.getByRole("button", { name: "メニューを畳む" }).click();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: "/tmp/netpolicy-policy-range-diff.png", fullPage: true, animations: "disabled" });
});
