version 17.12
hostname cisco-lab
ip routing
ipv6 unicast-routing
vlan 10
 name OFFICE
vlan 20
 name GUEST
vlan 90
 name SERVER
interface Vlan10
 ip address 10.44.1.1 255.255.255.0
 ipv6 address 2001:db8:44:1::1/64
 ip access-group OFFICE in
 ipv6 traffic-filter OFFICE6 in
interface Vlan20
 ip address 10.44.2.1 255.255.255.0
 ip access-group GUEST in
interface Vlan90
 ip address 10.44.9.1 255.255.255.0
 ipv6 address 2001:db8:44:9::1/64
ip access-list extended OFFICE
 10 deny tcp 10.44.1.0 0.0.0.255 10.44.9.0 0.0.0.255 eq 443
 20 deny ip any any
ip access-list extended GUEST
 10 deny ip any any
ipv6 access-list OFFICE6
 permit tcp 2001:db8:44:1::/64 2001:db8:44:9::/64 eq 443
 deny ipv6 any any
